[versions]
kotlin = "2.2.20"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
agp = "8.10.1"
androidx-activityCompose = "1.9.2"
compose-plugin = "1.9.1"
androidx-lifecycle = "2.9.3"
kotlinx-coroutines = "1.10.2"
binary-compatibility-validator = "0.18.1"
windowSizeClass = "0.5.0"
colorpicker = "1.1.2"
ktlint = "13.1.0"
publish = "0.33.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
windowSizeClass = { group = "dev.chrisbanes.material3", name = "material3-window-size-class-multiplatform", version.ref = "windowSizeClass" }
colorpicker = { group = "com.github.skydoves", name = "colorpicker-compose", version.ref = "colorpicker" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
binaryCompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
